### ISSUE TITLE
Arreglamos el método contarVocales

### ISSUE THREAD

**Issue by turpas** [turpas/turcasau#2]
Debemos buscar el fallo en el método y solucionarlo

**Comment by Capocalo14** [comment]
Cambiamos los "&&" por "||", los "!=" por "==" y lo hacemos también con las vocales con tilde, modificamos la siguiente linea.

if (caracter == 'a'  caracter == 'e'  caracter == 'i'  caracter == 'o'  caracter == 'u'  caracter == 'á'  caracter == 'é'  caracter == 'í'  caracter == 'ó' || caracter == 'ú')
