### ISSUE TITLE
Arreglamos método invertirPalabra

### ISSUE THREAD

**Issue by turpas** [turpas/turcasau#3]
Debemos buscar el fallo en el método y solucionarlo

**Comment by SAHJUL96** [comment]
vemos que invierte la palabra cada dos letras en vez de cada una. Modificamos la linea de la siguiente manera: for (int i = palabra.length() - 1; i >= 0; i--) {.

**Comment by SAHJUL96** [comment]
vemos que invierte la palabra cada dos letras en vez de cada una. Modificamos la linea de la siguiente manera: for (int i = palabra.length() - 1; i >= 0; i--).
